version: '2'

services:
  db:
    image: postgres
    volumes:
      - "./.data/db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis

  pgadmin:
    image: fenglc/pgadmin4
    volumes:
      - "./.data/pgadmin:/root/.pgadmin"
    ports:
      - "5050:5050"
    depends_on:
      - db

  web:
    build: .
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
      - redis
