# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 990ba348a503c96b714157f1952bc6b760d2ba985dc7c58cb3aba8eed6b500055bdf74fcb54526060bee942dde9835032ea8932c0e98c68e6994ec996675a348

test:
  secret_key_base: 8b0b7cbb15cc5b6e6430d09f3320952270ae44c67dd95340631fad852a46d0f254879188bb7bdf13e7ae3f66137e04c2c0641efd495074e952268c6050529a13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
